Fixes #11
sindresorhus/is-absolute-url pull request #12
Opened 2020-10-01 18:44 UTC by acagastya

Add potentially breaking change to check for `http[s]` URLs by default as requested.

2020-10-01 18:50 UTC, sindresorhus commented
This will also need docs and TypeScript type (following  https://github.com/sindresorhus/typescript-definition-style-guide) updates.

And give the PR a descriptive title.

2020-10-01 20:08 UTC, acagastya commented
I will update the docs and types shortly.  I have updated the PR title.  Thanks for pointing it out.

2020-10-01 20:35 UTC, acagastya commented
@sindresorhus I had updated `index.d.ts` by hovering over `module.exports` -- was it supposed to be done using any script?

2020-10-10 16:12 UTC, sindresorhus requested changes

2020-10-10 16:12 UTC, sindresorhus commented on test.js
> +	t.true(isAbsoluteUrl('https://sindresorhus.com', {httpOnly: true}));
The `false` option assertions should be in a separate test.

2020-10-10 16:12 UTC, sindresorhus commented on readme.md
> +By default only `http` and `https` links are validated.  If you wish to check absolute URLs of protocols other than `http` (for example, `ftp:`, `mailto:`), use `isAbsoluteUrl(mayBeURL, { httpOnly: f
These are not *links*.

2020-10-10 16:12 UTC, sindresorhus commented on readme.md
> +isAbsoluteUrl('ftp://sindresorhus.com/foo/bar', { httpOnly: false });
```suggestion
isAbsoluteUrl('ftp://sindresorhus.com/foo/bar', {httpOnly: false});
```

2020-10-10 16:12 UTC, sindresorhus commented on readme.md
> +By default only `http` and `https` links are validated.  If you wish to check absolute URLs of protocols other than `http` (for example, `ftp:`, `mailto:`), use `isAbsoluteUrl(mayBeURL, { httpOnly: f
The option should have proper API docs like done here: https://github.com/sindresorhus/boxen#api

2020-10-10 16:12 UTC, sindresorhus commented on readme.md
> +By default, it checks if the URL is of the `http` or `https` protocol.
I don't think "of" is correct here.

2020-10-10 16:12 UTC, sindresorhus commented on index.js
> +	return httpOnly ? /^https?:/.test(url) : /^[a-zA-Z][a-zA-Z\d+\-.]*:/.test(url);
```suggestion
	return httpOnly ? /^https?:\/\//.test(url) : /^[a-zA-Z][a-zA-Z\d+\-.]*:/.test(url);
```

2020-10-10 16:12 UTC, sindresorhus commented on index.d.ts
> +	{ httpOnly }?: { httpOnly?: boolean }
The options should be a separate type and have the same docs as the readme. Should follow: https://github.com/sindresorhus/typescript-definition-style-guide#documentation

2021-01-10 18:07 UTC, sindresorhus commented on index.d.ts
> +	{ httpOnly }?: { httpOnly?: boolean }
This is not fixed.

2021-01-10 18:09 UTC, sindresorhus commented on readme.md
> +By default only `http` and `https` links are validated.  If you wish to check absolute URLs of protocols other than `http` (for example, `ftp:`, `mailto:`), use `isAbsoluteUrl(mayBeURL, { httpOnly: f
This should be in the `httpOnly` option docs. Not here.

2021-01-10 18:10 UTC, sindresorhus commented on test.js
> +	t.true(isAbsoluteUrl('https://sindresorhus.com', {httpOnly: true}));
Please don't mark as resolved when things are in fact no resolved.

2021-03-07 11:12 UTC, sindresorhus commented
Bump

2021-06-03 19:05 UTC, sindresorhus commented
Bump

2021-08-10 22:55 UTC, closed without merging